version: 2
sphinx:
  configuration: doc/conf.py
python:
  install:
    - requirements: requirements-readthedocs.txt
build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - cd doc && doxygen
