name: Build artefacts
on: [push, pull_request]
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sdist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: pip install build==0.8.0
      - run: python -m build --sdist .
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: ./dist/*.tar.gz

  wheel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pypa/cibuildwheel@v2.10.2
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
